
url: http://pygmeeweb.com
language: en


name: Pygmeeweb
markdown: kramdown

kramdown:
  input: GFM

recent_posts: 50      # Posts on home page

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - Rakefile

disqus_shortname: pygmeeweb
